project:
  type: website

website:
  title: "Karl Ho blog of Data Science "
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/karlho
      - icon: twitter
        href: https://twitter.com/karlho
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

